version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ezcommit

  mysql:
    # Only for Apple M1
    platform: linux/x86_64
    image: mysql:8.0.25
    container_name: mysql
    ports:
      - "3306:3307"
    environment:
      MYSQL_ROOT_PASSWORD: ezcommit
